---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "cargo"
    allow:
      # Allow both direct and indirect updates for all packages.
      - dependency-type: "all"
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "cron"
      cronjob: "1 2 1,15 * *"
    # We want "increase-if-neccessary", but it's not supported for cargo.
    # See dependabot/dependabot-core#4009
    versioning-strategy: "lockfile-only"
